In [3]:
import cv2 as cv
import matplotlib.pyplot as plt 
import numpy as np

In [ ]:
img=cv.imread("tree.jpg")
kernal=np.ones((3,3),np.float32)/9
filter=cv.filter2D(img,-1,kernal)
cv.imshow("image",img)
cv.imshow("filter2d",filter)
cv.waitKey(0)
cv.destroyAllWindows()

# bluring

In [ ]:
img=cv.imread("tree.jpg")
blur=cv.blur(img,(5,5))
cv.imshow("image",img)
cv.imshow("blur",blur)
cv.waitKey(0)
cv.destroyAllWindows()

# Gaussian Blur

In [ ]:
img=cv.imread("noise.jpeg")
Gblur=cv.GaussianBlur(img,(5,5),0)
cv.imshow("image",img)
cv.imshow("Gaussianblur",Gblur)
cv.waitKey(0)
cv.destroyAllWindows()

# Bilateral Filter

In [ ]:
img=cv.imread("noise.jpeg")
bFilter=cv.bilateralFilter(img,10,20,20)
cv.imshow("image",img)
cv.imshow("bilateralFilter",bFilter)
cv.waitKey(0)
cv.destroyAllWindows()

# median Filters

In [ ]:
img=cv.imread("salt1.jpg")
m=cv.medianBlur(img,5)
cv.imshow("image",img)
cv.imshow("mideanFilter",m)
cv.waitKey(0)
cv.destroyAllWindows()

# Laplacian Filter

In [ ]:
img=cv.imread("noise.jpeg",0)
lap=cv.Laplacian(img,cv.CV_64F,ksize=3)
cv.imshow('image',img)
cv.imshow('laplacian',lap)
cv.waitKey(0)
cv.destroyAllWindows()

# Sobel Filter

In [5]:
img=cv.imread("noise.jpeg",0)
sobelx=cv.Sobel(img,cv.CV_32F,1,0,ksize=3)
print(sobelx)
cv.imshow('image',img)
cv.imshow("sobelx",sobelx)
cv.waitKey(0)
cv.destroyAllWindows()

[[   0.   16.  -22. ...    0.    0.    0.]
 [   0.    5.  -36. ...    0.    0.    0.]
 [   0.    7.  -36. ...    0.    0.    0.]
 ...
 [   0.   -9.   -9. ...  150.  173.    0.]
 [   0.   -8.   -9. ...  -18.  -74.    0.]
 [   0.   -2.   -4. ... -176.  -12.    0.]]


In [10]:
img=cv.imread("noise.jpeg",0)
sobely=cv.Sobel(img,cv.CV_32F,0,1,ksize=3)
print(sobely)
cv.imshow('image',img)
cv.imshow("sobely",sobely)
cv.waitKey(0)
cv.destroyAllWindows()

[[   0.    0.    0. ...    0.    0.    0.]
 [  48.   37.   12. ...    0.    0.    0.]
 [ -30.  -17.   10. ...    0.    0.    0.]
 ...
 [   4.   -1.  -11. ...  490.  171. -138.]
 [ -22.  -16.   -5. ... -208. -304. -242.]
 [   0.    0.    0. ...    0.    0.    0.]]
