In [1]:
import cv2
import numpy as np

In [2]:
a=cv2.imread("C:/Users/vishnu/Pictures/Screenshots/img9.jpeg",0)

In [3]:
cv2.imshow("img9",a)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
a

array([[107, 107, 107, ...,  62,  62,  62],
       [107, 107, 107, ...,  62,  62,  62],
       [107, 107, 107, ...,  62,  62,  62],
       ...,
       [114, 125, 130, ..., 183, 183, 183],
       [128, 132, 132, ..., 182, 182, 182],
       [127, 121, 118, ..., 172, 172, 172]], dtype=uint8)

In [5]:
ret,thres=cv2.threshold(a,11,100,cv2.THRESH_BINARY)

In [6]:
print(ret)

11.0


In [7]:
cv2.imshow("img",thres)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
thres

array([[100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100],
       ...,
       [100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100],
       [100, 100, 100, ..., 100, 100, 100]], dtype=uint8)

In [18]:
ret,thres1=cv2.threshold(a,86,256,cv2.THRESH_BINARY)
ret,thres2=cv2.threshold(a,86,256,cv2.THRESH_BINARY_INV)
ret,thres3=cv2.threshold(a,86,256,cv2.THRESH_TRUNC)
ret,thres4=cv2.threshold(a,86,256,cv2.THRESH_TOZERO)
ret,thres5=cv2.threshold(a,86,256,cv2.THRESH_TOZERO_INV)

In [19]:
thres1

array([[255, 255, 255, ...,   0,   0,   0],
       [255, 255, 255, ...,   0,   0,   0],
       [255, 255, 255, ...,   0,   0,   0],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [20]:
thres2

array([[  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [21]:
thres3


array([[86, 86, 86, ..., 62, 62, 62],
       [86, 86, 86, ..., 62, 62, 62],
       [86, 86, 86, ..., 62, 62, 62],
       ...,
       [86, 86, 86, ..., 86, 86, 86],
       [86, 86, 86, ..., 86, 86, 86],
       [86, 86, 86, ..., 86, 86, 86]], dtype=uint8)

In [22]:
thres4

array([[107, 107, 107, ...,   0,   0,   0],
       [107, 107, 107, ...,   0,   0,   0],
       [107, 107, 107, ...,   0,   0,   0],
       ...,
       [114, 125, 130, ..., 183, 183, 183],
       [128, 132, 132, ..., 182, 182, 182],
       [127, 121, 118, ..., 172, 172, 172]], dtype=uint8)

In [23]:
thres5

array([[ 0,  0,  0, ..., 62, 62, 62],
       [ 0,  0,  0, ..., 62, 62, 62],
       [ 0,  0,  0, ..., 62, 62, 62],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=uint8)

In [26]:
cv2.imshow("img1",thres1)
cv2.waitKey(0)
cv2.imshow("img2",thres2)
cv2.waitKey(0)
cv2.imshow("img3",thres3)
cv2.waitKey(0)
cv2.imshow("img4",thres4)
cv2.waitKey(0)
cv2.imshow("img5",thres5)
cv2.waitKey(0)
cv2.destroyAllWindows()