In [1]:
import cv2 
import numpy as np

In [2]:
a=cv2.imread("C:/Users/admin/Downloads/img4.jpg")

In [3]:
a


array([[[206, 198, 191],
        [206, 198, 191],
        [206, 198, 191],
        ...,
        [223, 218, 217],
        [223, 218, 217],
        [223, 218, 217]],

       [[206, 198, 191],
        [206, 198, 191],
        [206, 198, 191],
        ...,
        [223, 218, 217],
        [223, 218, 217],
        [223, 218, 217]],

       [[206, 198, 191],
        [206, 198, 191],
        [206, 198, 191],
        ...,
        [223, 218, 217],
        [223, 218, 217],
        [223, 218, 217]],

       ...,

       [[194, 185, 176],
        [194, 185, 176],
        [194, 185, 176],
        ...,
        [174, 158, 146],
        [174, 158, 146],
        [174, 158, 146]],

       [[194, 185, 176],
        [194, 185, 176],
        [194, 185, 176],
        ...,
        [174, 158, 146],
        [174, 158, 146],
        [174, 158, 146]],

       [[194, 185, 176],
        [194, 185, 176],
        [194, 185, 176],
        ...,
        [174, 158, 146],
        [174, 158, 146],
        [174, 158, 146]]

In [4]:
shape=a.shape

In [5]:
shape

(612, 612, 3)

In [6]:
height,width=a.shape[:2]
print(height)
print(width)

612
612


In [7]:
c=(height/2,width/2)
c

(306.0, 306.0)

In [8]:
#Rotation matrix
rm=cv2.getRotationMatrix2D(center=c,angle=180,scale=0.6)

In [9]:
rm

array([[-6.00000000e-01,  7.34788079e-17,  4.89600000e+02],
       [-7.34788079e-17, -6.00000000e-01,  4.89600000e+02]])

In [10]:
#Rotated image
ri=cv2.warpAffine(src=a,M=rm,dsize=(width, height))

In [17]:
cv2.imshow("Original image",a)
cv2.waitKey(0)
cv2.imshow("Rotated image",ri)
cv2.waitKey(0)
cv2.destroyAllWindows()

# TRANSLATION MATRIX



In [18]:
tx,ty=width/2,height/2

In [19]:
#Translation Matrix
tm=np.array([[1,0,tx],[0,1,ty]])


In [20]:
tm

array([[  1.,   0., 306.],
       [  0.,   1., 306.]])

In [21]:
ti=cv2.warpAffine(src=a,M=tm,dsize=(width, height))

In [22]:
cv2.imshow("Original image",a)
cv2.waitKey(0)
cv2.imshow("Translation image",ti)
cv2.waitKey(0)
cv2.destroyAllWindows()